/**
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef _DEF_RTAC_PLOT_PLOT_SURFACE_H_
#define _DEF_RTAC_PLOT_PLOT_SURFACE_H_

#include <memory>

#include <rtac_base/types/Bounds.h>
#include <rtac_display/DrawingSurface.h>

#include <rtac_plot/PlotView2D.h>

namespace rtac { namespace plot {

class PlotSurface : public rtac::display::DrawingSurface
{
    public:

    using Ptr      = std::shared_ptr<PlotSurface>;
    using ConstPtr = std::shared_ptr<const PlotSurface>;

    using Extent = PlotView2D::Extent;

    protected:
    
    PlotView2D::Ptr view_;
    Extent extent_;          // this is the max extent of display area, max zoom
    Extent displayedExtent_;

    PlotSurface(display::GLContext::Ptr context,
                const Extent& extent);

    public:
    
    static Ptr Create(display::GLContext::Ptr context,
                      const Extent& extent = Extent{{{-1.0f,1.0f},
                                                     {-1.0f,1.0f}}});

    PlotView2D::ConstPtr view() const { return view_; }
};

} //namespace plot
} //namespace rtac


#endif //_DEF_RTAC_PLOT_PLOT_SURFACE_H_
